from __future__ import annotations

from typing import Any


def build_condition_comparison_matrix() -> list[dict[str, Any]]:
    common_boundary = "Research framing only; not diagnostic and not sufficient for clinical inference."
    return [
        {
            "condition": "occipital_focal_aware_seizure_visual_aura",
            "typical_duration_pattern": "seconds to a few minutes",
            "onset_pattern": "often abrupt",
            "visual_quality_pattern": "colored shapes, flicker, field-limited visual phenomena",
            "awareness_pattern": "may be retained in focal aware episodes",
            "trigger_pattern": "may be spontaneous; trigger claims require clinical review",
            "EEG_relevance": "event-aligned EEG may be research-relevant after adapter review",
            "red_flags": "loss of awareness, motor symptoms, injury, new neurologic deficits",
            "limits_of_inference": "symptom structure alone cannot distinguish seizure from mimics",
            "claim_boundary": common_boundary,
        },
        {
            "condition": "reflex_photosensitive_seizure_activity",
            "typical_duration_pattern": "seconds to minutes around visual stimulus exposure",
            "onset_pattern": "temporally linked to flicker/pattern exposure when clinically confirmed",
            "visual_quality_pattern": "flicker sensitivity or pattern sensitivity may be reported",
            "awareness_pattern": "variable",
            "trigger_pattern": "photic or patterned stimuli, but NV-1 must not recommend trigger testing",
            "EEG_relevance": "photic stimulation metadata is relevant only in supervised datasets",
            "red_flags": "known epilepsy history, provoked events, impaired awareness",
            "limits_of_inference": "no unsupervised photic testing or safety claim",
            "claim_boundary": common_boundary,
        },
        {
            "condition": "migraine_aura",
            "typical_duration_pattern": "often gradual and minutes-long",
            "onset_pattern": "spreading or progressive symptoms can occur",
            "visual_quality_pattern": "scintillation, scotoma, zig-zag, spreading phenomena",
            "awareness_pattern": "typically retained",
            "trigger_pattern": "sleep, stress, light, hormonal, dietary, or other context may matter",
            "EEG_relevance": "EEG is not a stand-alone migraine aura diagnostic test",
            "red_flags": "first or worst headache, neurologic deficit, atypical course",
            "limits_of_inference": "symptom mapping is not migraine diagnosis",
            "claim_boundary": common_boundary,
        },
        {
            "condition": "visual_snow_syndrome",
            "typical_duration_pattern": "persistent or recurrent visual static-like symptoms",
            "onset_pattern": "often chronic rather than brief events",
            "visual_quality_pattern": "static, afterimages, photophobia, entoptic phenomena",
            "awareness_pattern": "retained",
            "trigger_pattern": "visual context may modulate symptoms",
            "EEG_relevance": "EEG relevance must be dataset-specific and cannot diagnose",
            "red_flags": "new neurologic symptoms or acute visual loss",
            "limits_of_inference": "not a visual snow detector",
            "claim_boundary": common_boundary,
        },
        {
            "condition": "concussion_related_visual_symptoms",
            "typical_duration_pattern": "variable after head injury",
            "onset_pattern": "after concussion or head/neck trauma context",
            "visual_quality_pattern": "tracking difficulty, light sensitivity, dizziness-associated visual issues",
            "awareness_pattern": "variable depending on injury context",
            "trigger_pattern": "screens, motion, reading, or vestibular load",
            "EEG_relevance": "EEG is adjunct research context only",
            "red_flags": "worsening headache, confusion, repeated vomiting, focal deficits",
            "limits_of_inference": "not a concussion diagnosis",
            "claim_boundary": common_boundary,
        },
        {
            "condition": "panic_derealization_episodes",
            "typical_duration_pattern": "minutes to longer episodes",
            "onset_pattern": "may build with autonomic alarm symptoms",
            "visual_quality_pattern": "derealization or altered salience rather than new objects",
            "awareness_pattern": "usually retained",
            "trigger_pattern": "stress, context, interoceptive cues",
            "EEG_relevance": "EEG is not a psychiatric diagnosis tool",
            "red_flags": "new neurologic signs or impaired awareness",
            "limits_of_inference": "not a psychiatric condition detector",
            "claim_boundary": common_boundary,
        },
        {
            "condition": "functional_psychogenic_episodes",
            "typical_duration_pattern": "variable",
            "onset_pattern": "context-dependent and heterogeneous",
            "visual_quality_pattern": "variable subjective symptoms",
            "awareness_pattern": "variable",
            "trigger_pattern": "requires specialist evaluation",
            "EEG_relevance": "EEG interpretation requires clinical context",
            "red_flags": "injury, impaired awareness, neurologic deficits",
            "limits_of_inference": "not an adjudication engine",
            "claim_boundary": common_boundary,
        },
        {
            "condition": "medication_substance_metabolic_contributors",
            "typical_duration_pattern": "linked to exposure or physiologic context",
            "onset_pattern": "variable",
            "visual_quality_pattern": "blur, glare, altered perception, tremor-associated visual issues",
            "awareness_pattern": "variable",
            "trigger_pattern": "medication, stimulant, sleep, hydration, metabolic context",
            "EEG_relevance": "confounder context for research review",
            "red_flags": "acute toxicity, altered mental status, severe neurologic symptoms",
            "limits_of_inference": "not medication guidance",
            "claim_boundary": common_boundary,
        },
    ]
